version: '3.6'

services:
  server:
    image: server
    build:
      context: .
    command: server "tcp://*:5557"

  client:
    image: client
    build:
      context: .
    depends_on:
      - "server"
    volumes:
      - ./files:/opt/transfer/files
    # # Pass stdin through to the executable.
    # stdin_open: true
    # tty: true
    command: client "tcp://server:5557" files/cad_mesh.stl